language: python

python:
    - "3.8"

branches:
    only:
    - master

services:
    - docker

#before_script: docker pull mkroutikov/redstork:latest

script:
    - PWD=`pwd`
    - echo docker run -v `pwd`:/self mkroutikov/redstork:latest bash -c "make wheel"
    - docker run -v `pwd`:/self mkroutikov/redstork:latest bash -c "make wheel"
    - pip install twine

deploy:
    provider: pypi
    distributions: "bdist_wheel"
    skip_cleanup: true
    on:
        tags: true
    user: "__token__"
    password:
        secure: "Your encrypted token"

