language: python

python:
    - "3.8"

branches:
    only:
    - master

services:
    - docker

#before_script: docker pull mkroutikov/redstork:latest

script:
    - docker run -v `pwd`:/pdfium/redstork mkroutikov/redstork:latest make wheel
    - ls -l redstork/linux

deploy:
    provider: pypi
    distributions: "bdist_wheel"
    skip_cleanup: true
    on:
        tags: true
    user: "__token__"
    password:
        secure: "Your encrypted token"

