language: python

python:
    - "3.8"

branches:
    only:
    - master

services:
    - docker

script:
    - docker run -v `pwd`:/pdfium/redstork mkroutikov/redstork:latest make wheel
    - pip install pytest wheel
    - pytest

deploy:
    provider: pypi
    distributions: "bdist_wheel"
    skip_cleanup: true
    user: "__token__"
    password: $PYPI_TOKEN

notifications:
    slack: $SLACK_TOKEN
