language: python

python:
    - "3.8"

services:
    - docker

before_script: docker pull mkroutikov/redstork:latest

script:
    - docker run -v`pwd`:/self mkroutikov/redstork:latest bash -c "make wheel"

deploy:
    provider: pypi
    user: "__token__"
    password:
        secure: "Your encrypted token"

